import type { CheckResult } from "@/app/api/vibe-check/route";
import type { ApiEntry, DocumentResult } from "@/types/explanation";
import type { BlueprintResult } from "@/types/blueprint";
import type { PolishResult } from "@/types/polish";

export interface ShipCheckExportData {
  repoUrl: string;
  shipScore: number;
  verdict: string;
  builderType: string;
  assessment: string;
  checks: CheckResult[];
  techStack: string;
}

export interface DefendExportData {
  repoUrl: string;
  defenseScore: number;
  builderType: string;
  assessment: string;
  weakSpots: string[];
  answered: {
    id: number;
    category: string;
    question: string;
    answer: string;
    score: number;
    feedback: string;
  }[];
}

export function exportShipCheckMarkdown(data: ShipCheckExportData): string {
  const { repoUrl, shipScore, verdict, builderType, assessment, checks, techStack } = data;
  const passed = checks.filter((c) => c.passed);
  const failed = checks.filter((c) => !c.passed);
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const lines: string[] = [
    `# Ship Check Report`,
    ``,
    `**Repository:** ${repoUrl}  `,
    `**Date:** ${date}  `,
    `**Ship Score:** ${shipScore}/100  `,
    `**Verdict:** ${verdict}  `,
    builderType ? `**Builder Type:** ${builderType}  ` : "",
    `**Tech Stack:** ${techStack}  `,
    ``,
  ].filter((l) => l !== undefined);

  if (assessment) {
    lines.push(`## Assessment`, ``, assessment, ``);
  }

  if (passed.length > 0) {
    lines.push(`## Passed Checks`, ``);
    for (const c of passed) {
      lines.push(`- ✅ **${c.name}**`);
    }
    lines.push(``);
  }

  if (failed.length > 0) {
    lines.push(`## Failed Checks`, ``);
    for (const c of failed) {
      lines.push(`### ❌ ${c.name}`);
      if (c.findings.length > 0) {
        for (const f of c.findings.slice(0, 4)) {
          lines.push(
            `- \`${f.file}${f.line ? `:${f.line}` : ""}\` — ${f.detail}`
          );
        }
      }
      lines.push(``);
    }
  }

  lines.push(`---`, `*Generated by [PlainCode](https://plaincode-production.up.railway.app)*`);

  return lines.join("\n");
}

export interface DocumentExportData {
  title: string;
  overview: string;
  purpose: string;
  apiEntries: ApiEntry[];
  steps: string;
  flowchart: string;
  sequenceDiagram: string;
  dataflow: string;
  example: string;
  edgeCases: string;
  complexity: string;
  detectedLanguage: string;
}

function escapeTableCell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n+/g, " ");
}

function renderApiTable(entries: ApiEntry[]): string[] {
  if (entries.length === 0) return [];
  const out: string[] = [];
  for (const entry of entries) {
    out.push(`### \`${entry.signature}\``, ``, entry.description, ``);
    if (entry.params.length > 0) {
      out.push(`**Parameters**`, ``, `| Name | Type | Description |`, `| --- | --- | --- |`);
      for (const p of entry.params) {
        const name = p.optional ? `${p.name}?` : p.name;
        out.push(`| \`${escapeTableCell(name)}\` | \`${escapeTableCell(p.type)}\` | ${escapeTableCell(p.description)} |`);
      }
      out.push(``);
    }
    if (entry.returns && entry.returns.type) {
      out.push(`**Returns:** \`${entry.returns.type}\` — ${entry.returns.description}`, ``);
    }
    if (entry.throws.length > 0) {
      out.push(`**Throws**`, ``);
      for (const t of entry.throws) {
        out.push(`- \`${t.type}\` — ${t.description}`);
      }
      out.push(``);
    }
  }
  return out;
}

export function exportDocumentMarkdown(data: DocumentExportData): string {
  const {
    title,
    overview,
    purpose,
    apiEntries,
    steps,
    flowchart,
    sequenceDiagram,
    dataflow,
    example,
    edgeCases,
    complexity,
    detectedLanguage,
  } = data;
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const lines: string[] = [`# ${title || "Documentation"}`, ``, `*Generated: ${date}*`, ``];

  if (overview) lines.push(`## Overview`, ``, overview, ``);
  if (purpose) lines.push(`## Purpose`, ``, purpose, ``);

  if (apiEntries.length > 0) {
    lines.push(`## API Reference`, ``);
    lines.push(...renderApiTable(apiEntries));
  }

  if (steps) lines.push(`## Step-by-Step`, ``, steps, ``);

  if (flowchart) {
    lines.push(`## Control Flow`, ``, "```mermaid", flowchart.trim(), "```", ``);
  }
  if (sequenceDiagram) {
    lines.push(`## Sequence`, ``, "```mermaid", sequenceDiagram.trim(), "```", ``);
  }
  if (dataflow) {
    lines.push(`## Data Flow`, ``, "```mermaid", dataflow.trim(), "```", ``);
  }

  if (example) {
    const langTag = (detectedLanguage || "").toLowerCase();
    lines.push(`## Usage Example`, ``, "```" + langTag, example.trim(), "```", ``);
  }

  if (edgeCases) lines.push(`## Edge Cases & Gotchas`, ``, edgeCases, ``);
  if (complexity) lines.push(`## Complexity & Performance`, ``, complexity, ``);

  lines.push(`---`, `*Generated by [PlainCode](https://plaincode-production.up.railway.app)*`);

  return lines.join("\n");
}

function buildJsDocBlock(entry: ApiEntry): string {
  const lines: string[] = ["/**", ` * ${entry.description}`];
  if (entry.params.length > 0) lines.push(` *`);
  for (const p of entry.params) {
    const name = p.optional ? `[${p.name}]` : p.name;
    lines.push(` * @param {${p.type}} ${name} ${p.description}`);
  }
  if (entry.returns && entry.returns.type) {
    lines.push(` * @returns {${entry.returns.type}} ${entry.returns.description}`);
  }
  for (const t of entry.throws) {
    lines.push(` * @throws {${t.type}} ${t.description}`);
  }
  lines.push(" */");
  return lines.join("\n");
}

function buildPythonDocstring(entry: ApiEntry): string {
  const lines: string[] = [`"""${entry.description}`, ``];
  if (entry.params.length > 0) {
    lines.push("Args:");
    for (const p of entry.params) {
      lines.push(`    ${p.name} (${p.type}): ${p.description}`);
    }
    lines.push("");
  }
  if (entry.returns && entry.returns.type) {
    lines.push("Returns:", `    ${entry.returns.type}: ${entry.returns.description}`, ``);
  }
  if (entry.throws.length > 0) {
    lines.push("Raises:");
    for (const t of entry.throws) {
      lines.push(`    ${t.type}: ${t.description}`);
    }
    lines.push("");
  }
  lines.push(`"""`);
  return lines.map((l, i) => (i === 0 ? l : "    " + l)).join("\n");
}

function buildGenericBlock(entry: ApiEntry): string {
  const lines: string[] = [`// ${entry.signature}`, `// ${entry.description}`];
  for (const p of entry.params) {
    lines.push(`//   @param ${p.name} (${p.type}) — ${p.description}`);
  }
  if (entry.returns?.type) {
    lines.push(`//   @returns ${entry.returns.type} — ${entry.returns.description}`);
  }
  for (const t of entry.throws) {
    lines.push(`//   @throws ${t.type} — ${t.description}`);
  }
  return lines.join("\n");
}

export function exportDocstrings(entries: ApiEntry[], detectedLanguage: string): string {
  if (entries.length === 0) return "";
  const lang = detectedLanguage.toLowerCase();
  const isJsTs = /(javascript|typescript|jsx|tsx|node|js|ts)/.test(lang);
  const isPython = /python|py/.test(lang);

  const builder = isJsTs
    ? buildJsDocBlock
    : isPython
      ? buildPythonDocstring
      : buildGenericBlock;

  return entries
    .map((e) => `${builder(e)}\n${e.signature}`)
    .join("\n\n");
}

/* ── Docstring injection into original source ──────────────────────────── */

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function leadingWhitespace(line: string): string {
  return line.match(/^[ \t]*/)?.[0] ?? "";
}

function indentBlock(block: string, indent: string): string {
  return block
    .split("\n")
    .map((l) => (l.length > 0 ? indent + l : l))
    .join("\n");
}

function findDefLineJsLike(lines: string[], name: string): number {
  const n = escapeRegExp(name);
  const patterns = [
    new RegExp(`\\b(?:export\\s+)?(?:default\\s+)?(?:async\\s+)?function\\*?\\s+${n}\\b`),
    new RegExp(`\\b(?:export\\s+)?(?:abstract\\s+)?class\\s+${n}\\b`),
    new RegExp(`\\b(?:export\\s+)?(?:const|let|var)\\s+${n}\\s*=`),
    new RegExp(`\\b${n}\\s*\\([^)]*\\)\\s*[:{]`), // method definition
    new RegExp(`\\b${n}\\s*[:=]\\s*(?:async\\s*)?\\(`), // arrow property
  ];
  for (let i = 0; i < lines.length; i++) {
    if (patterns.some((p) => p.test(lines[i]))) return i;
  }
  return -1;
}

function findDefLinePython(lines: string[], name: string): number {
  const p = new RegExp(`^\\s*(?:async\\s+)?(?:def|class)\\s+${escapeRegExp(name)}\\b`);
  for (let i = 0; i < lines.length; i++) {
    if (p.test(lines[i])) return i;
  }
  return -1;
}

// Python signatures can span multiple lines; the body starts after the line
// whose code (stripped of trailing comment) ends with a colon.
function findPythonSignatureEnd(lines: string[], defLine: number): number {
  for (let i = defLine; i < lines.length; i++) {
    const code = lines[i].replace(/#.*$/, "").trimEnd();
    if (code.endsWith(":")) return i;
  }
  return defLine;
}

function buildPythonDocstringFlat(entry: ApiEntry): string {
  const out: string[] = [`"""${entry.description}`];
  if (entry.params.length > 0) {
    out.push("", "Args:");
    for (const p of entry.params) out.push(`    ${p.name} (${p.type}): ${p.description}`);
  }
  if (entry.returns && entry.returns.type) {
    out.push("", "Returns:", `    ${entry.returns.type}: ${entry.returns.description}`);
  }
  if (entry.throws.length > 0) {
    out.push("", "Raises:");
    for (const t of entry.throws) out.push(`    ${t.type}: ${t.description}`);
  }
  out.push(`"""`);
  return out.join("\n");
}

export interface InjectResult {
  code: string;
  injected: number;
  skipped: string[];
}

/**
 * Inserts generated doc-comments into the original source at each function /
 * class definition. Best-effort: entries whose definition can't be located are
 * left untouched and reported in `skipped`. Never throws — returns the original
 * code unchanged if nothing matches.
 */
export function injectDocstrings(
  code: string,
  entries: ApiEntry[],
  detectedLanguage: string
): InjectResult {
  if (!code || entries.length === 0) {
    return { code, injected: 0, skipped: entries.map((e) => e.name) };
  }

  const lang = detectedLanguage.toLowerCase();
  const isPython = /python|py/.test(lang);
  const isJsTs = /(javascript|typescript|jsx|tsx|node|js|ts)/.test(lang);

  const lines = code.split("\n");

  // Resolve each entry to an insertion plan first, then apply bottom-up so
  // earlier line indices stay valid as we splice.
  interface Plan {
    insertAt: number; // index to splice the block before
    block: string;
    name: string;
  }
  const plans: Plan[] = [];
  const skipped: string[] = [];

  for (const entry of entries) {
    if (isPython) {
      const defLine = findDefLinePython(lines, entry.name);
      if (defLine === -1) {
        skipped.push(entry.name);
        continue;
      }
      const sigEnd = findPythonSignatureEnd(lines, defLine);
      const bodyIndent = leadingWhitespace(lines[defLine]) + "    ";
      const block = indentBlock(buildPythonDocstringFlat(entry), bodyIndent);
      plans.push({ insertAt: sigEnd + 1, block, name: entry.name });
    } else {
      const defLine = findDefLineJsLike(lines, entry.name);
      if (defLine === -1) {
        skipped.push(entry.name);
        continue;
      }
      const indent = leadingWhitespace(lines[defLine]);
      const rawBlock = isJsTs ? buildJsDocBlock(entry) : buildGenericBlock(entry);
      const block = indentBlock(rawBlock, indent);
      plans.push({ insertAt: defLine, block, name: entry.name });
    }
  }

  // Apply bottom-up to preserve indices.
  plans.sort((a, b) => b.insertAt - a.insertAt);
  for (const plan of plans) {
    lines.splice(plan.insertAt, 0, plan.block);
  }

  return { code: lines.join("\n"), injected: plans.length, skipped };
}

export function exportDefendMarkdown(data: DefendExportData): string {
  const { repoUrl, defenseScore, builderType, assessment, weakSpots, answered } = data;
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const lines: string[] = [
    `# Defend Report`,
    ``,
    `**Repository:** ${repoUrl}  `,
    `**Date:** ${date}  `,
    `**Defense Score:** ${defenseScore}/100  `,
    builderType ? `**Builder Type:** ${builderType}  ` : "",
    ``,
  ].filter((l) => l !== undefined);

  if (assessment) {
    lines.push(`## Assessment`, ``, assessment, ``);
  }

  if (weakSpots.length > 0) {
    lines.push(`## Weak Spots`, ``);
    for (const spot of weakSpots) {
      lines.push(`- ${spot}`);
    }
    lines.push(``);
  }

  if (answered.length > 0) {
    lines.push(`## Q&A Breakdown`, ``);
    for (const a of answered) {
      lines.push(
        `### ${a.category} — ${a.score}/100`,
        ``,
        `**Question:** ${a.question}`,
        ``,
        `**Answer:** ${a.answer}`,
        ``,
        `**Feedback:** ${a.feedback}`,
        ``
      );
    }
  }

  lines.push(`---`, `*Generated by [PlainCode](https://plaincode-production.up.railway.app)*`);

  return lines.join("\n");
}

/* ── Blueprint mode ────────────────────────────────────────────────────────── */

const BLUEPRINT_PROMPT_LABELS: Record<keyof BlueprintResult["prompts"], string> = {
  codex: "Codex",
  claude: "Claude",
  chatgpt: "ChatGPT",
  cursor: "Cursor",
  generic: "Any AI agent",
};

export function exportBlueprintMarkdown(result: BlueprintResult): string {
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const lines: string[] = [result.blueprintMarkdown.trim(), ``, `## AI Build Prompts`, ``];

  for (const key of Object.keys(result.prompts) as (keyof BlueprintResult["prompts"])[]) {
    lines.push(`### ${BLUEPRINT_PROMPT_LABELS[key]}`, ``, "```text", result.prompts[key].trim(), "```", ``);
  }

  lines.push(`*Generated: ${date}*`, `---`, `*Generated by [PlainCode](https://plaincode-production.up.railway.app)*`);

  return lines.join("\n");
}

/* ── Polish mode ───────────────────────────────────────────────────────────── */

const POLISH_PROMPT_LABELS: Record<keyof PolishResult["prompts"], string> = {
  codex: "Codex",
  claude: "Claude",
  chatgpt: "ChatGPT",
  cursor: "Cursor",
  generic: "Any AI agent",
};

export function exportPolishMarkdown(result: PolishResult): string {
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const lines: string[] = [result.designMd.trim(), ``, `## Design Tokens`, ``];

  lines.push(`### Tailwind`, ``, "```css", result.tokens.tailwind.trim(), "```", ``);
  lines.push(`### CSS Variables`, ``, "```css", result.tokens.css.trim(), "```", ``);
  lines.push(`### JSON`, ``, "```json", result.tokens.json.trim(), "```", ``);

  if (result.critiqueTrail?.length) {
    lines.push(`## Quality passes`, ``);
    result.critiqueTrail.forEach((c, i) => {
      lines.push(`- **Pass ${i + 1}: ${c.score}/100** — ${c.verdict}`);
    });
    lines.push(``);
  }

  if (result.screens.length) {
    lines.push(`## Rendered Screens`, ``);
    for (const s of result.screens) {
      lines.push(`### ${s.name}`, ``, "```html", s.html.trim(), "```", ``);
    }
  }

  lines.push(`## Apply-this-design Prompts`, ``);
  for (const key of Object.keys(result.prompts) as (keyof PolishResult["prompts"])[]) {
    lines.push(`### ${POLISH_PROMPT_LABELS[key]}`, ``, "```text", result.prompts[key].trim(), "```", ``);
  }

  lines.push(`*Generated: ${date}*`, `---`, `*Generated by [PlainCode](https://plaincode-production.up.railway.app)*`);

  return lines.join("\n");
}
