import type { CheckResult } from "@/app/api/vibe-check/route";

export interface ShipCheckExportData {
  repoUrl: string;
  shipScore: number;
  verdict: string;
  builderType: string;
  assessment: string;
  checks: CheckResult[];
  techStack: string;
}

export interface DefendExportData {
  repoUrl: string;
  defenseScore: number;
  builderType: string;
  assessment: string;
  weakSpots: string[];
  answered: {
    id: number;
    category: string;
    question: string;
    answer: string;
    score: number;
    feedback: string;
  }[];
}

export function exportShipCheckMarkdown(data: ShipCheckExportData): string {
  const { repoUrl, shipScore, verdict, builderType, assessment, checks, techStack } = data;
  const passed = checks.filter((c) => c.passed);
  const failed = checks.filter((c) => !c.passed);
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const lines: string[] = [
    `# Ship Check Report`,
    ``,
    `**Repository:** ${repoUrl}  `,
    `**Date:** ${date}  `,
    `**Ship Score:** ${shipScore}/100  `,
    `**Verdict:** ${verdict}  `,
    builderType ? `**Builder Type:** ${builderType}  ` : "",
    `**Tech Stack:** ${techStack}  `,
    ``,
  ].filter((l) => l !== undefined);

  if (assessment) {
    lines.push(`## Assessment`, ``, assessment, ``);
  }

  if (passed.length > 0) {
    lines.push(`## Passed Checks`, ``);
    for (const c of passed) {
      lines.push(`- ✅ **${c.name}**`);
    }
    lines.push(``);
  }

  if (failed.length > 0) {
    lines.push(`## Failed Checks`, ``);
    for (const c of failed) {
      lines.push(`### ❌ ${c.name}`);
      if (c.findings.length > 0) {
        for (const f of c.findings.slice(0, 4)) {
          lines.push(
            `- \`${f.file}${f.line ? `:${f.line}` : ""}\` — ${f.detail}`
          );
        }
      }
      lines.push(``);
    }
  }

  lines.push(`---`, `*Generated by [PlainCode](https://plaincode-production.up.railway.app)*`);

  return lines.join("\n");
}

export function exportDefendMarkdown(data: DefendExportData): string {
  const { repoUrl, defenseScore, builderType, assessment, weakSpots, answered } = data;
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const lines: string[] = [
    `# Defend Report`,
    ``,
    `**Repository:** ${repoUrl}  `,
    `**Date:** ${date}  `,
    `**Defense Score:** ${defenseScore}/100  `,
    builderType ? `**Builder Type:** ${builderType}  ` : "",
    ``,
  ].filter((l) => l !== undefined);

  if (assessment) {
    lines.push(`## Assessment`, ``, assessment, ``);
  }

  if (weakSpots.length > 0) {
    lines.push(`## Weak Spots`, ``);
    for (const spot of weakSpots) {
      lines.push(`- ${spot}`);
    }
    lines.push(``);
  }

  if (answered.length > 0) {
    lines.push(`## Q&A Breakdown`, ``);
    for (const a of answered) {
      lines.push(
        `### ${a.category} — ${a.score}/100`,
        ``,
        `**Question:** ${a.question}`,
        ``,
        `**Answer:** ${a.answer}`,
        ``,
        `**Feedback:** ${a.feedback}`,
        ``
      );
    }
  }

  lines.push(`---`, `*Generated by [PlainCode](https://plaincode-production.up.railway.app)*`);

  return lines.join("\n");
}
