import type { CheckResult } from "@/app/api/vibe-check/route";
import type { ApiEntry, DocumentResult } from "@/types/explanation";

export interface ShipCheckExportData {
  repoUrl: string;
  shipScore: number;
  verdict: string;
  builderType: string;
  assessment: string;
  checks: CheckResult[];
  techStack: string;
}

export interface DefendExportData {
  repoUrl: string;
  defenseScore: number;
  builderType: string;
  assessment: string;
  weakSpots: string[];
  answered: {
    id: number;
    category: string;
    question: string;
    answer: string;
    score: number;
    feedback: string;
  }[];
}

export function exportShipCheckMarkdown(data: ShipCheckExportData): string {
  const { repoUrl, shipScore, verdict, builderType, assessment, checks, techStack } = data;
  const passed = checks.filter((c) => c.passed);
  const failed = checks.filter((c) => !c.passed);
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const lines: string[] = [
    `# Ship Check Report`,
    ``,
    `**Repository:** ${repoUrl}  `,
    `**Date:** ${date}  `,
    `**Ship Score:** ${shipScore}/100  `,
    `**Verdict:** ${verdict}  `,
    builderType ? `**Builder Type:** ${builderType}  ` : "",
    `**Tech Stack:** ${techStack}  `,
    ``,
  ].filter((l) => l !== undefined);

  if (assessment) {
    lines.push(`## Assessment`, ``, assessment, ``);
  }

  if (passed.length > 0) {
    lines.push(`## Passed Checks`, ``);
    for (const c of passed) {
      lines.push(`- ✅ **${c.name}**`);
    }
    lines.push(``);
  }

  if (failed.length > 0) {
    lines.push(`## Failed Checks`, ``);
    for (const c of failed) {
      lines.push(`### ❌ ${c.name}`);
      if (c.findings.length > 0) {
        for (const f of c.findings.slice(0, 4)) {
          lines.push(
            `- \`${f.file}${f.line ? `:${f.line}` : ""}\` — ${f.detail}`
          );
        }
      }
      lines.push(``);
    }
  }

  lines.push(`---`, `*Generated by [PlainCode](https://plaincode-production.up.railway.app)*`);

  return lines.join("\n");
}

export interface DocumentExportData {
  title: string;
  overview: string;
  purpose: string;
  apiEntries: ApiEntry[];
  steps: string;
  flowchart: string;
  sequenceDiagram: string;
  dataflow: string;
  example: string;
  edgeCases: string;
  complexity: string;
  detectedLanguage: string;
}

function escapeTableCell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n+/g, " ");
}

function renderApiTable(entries: ApiEntry[]): string[] {
  if (entries.length === 0) return [];
  const out: string[] = [];
  for (const entry of entries) {
    out.push(`### \`${entry.signature}\``, ``, entry.description, ``);
    if (entry.params.length > 0) {
      out.push(`**Parameters**`, ``, `| Name | Type | Description |`, `| --- | --- | --- |`);
      for (const p of entry.params) {
        const name = p.optional ? `${p.name}?` : p.name;
        out.push(`| \`${escapeTableCell(name)}\` | \`${escapeTableCell(p.type)}\` | ${escapeTableCell(p.description)} |`);
      }
      out.push(``);
    }
    if (entry.returns && entry.returns.type) {
      out.push(`**Returns:** \`${entry.returns.type}\` — ${entry.returns.description}`, ``);
    }
    if (entry.throws.length > 0) {
      out.push(`**Throws**`, ``);
      for (const t of entry.throws) {
        out.push(`- \`${t.type}\` — ${t.description}`);
      }
      out.push(``);
    }
  }
  return out;
}

export function exportDocumentMarkdown(data: DocumentExportData): string {
  const {
    title,
    overview,
    purpose,
    apiEntries,
    steps,
    flowchart,
    sequenceDiagram,
    dataflow,
    example,
    edgeCases,
    complexity,
    detectedLanguage,
  } = data;
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const lines: string[] = [`# ${title || "Documentation"}`, ``, `*Generated: ${date}*`, ``];

  if (overview) lines.push(`## Overview`, ``, overview, ``);
  if (purpose) lines.push(`## Purpose`, ``, purpose, ``);

  if (apiEntries.length > 0) {
    lines.push(`## API Reference`, ``);
    lines.push(...renderApiTable(apiEntries));
  }

  if (steps) lines.push(`## Step-by-Step`, ``, steps, ``);

  if (flowchart) {
    lines.push(`## Control Flow`, ``, "```mermaid", flowchart.trim(), "```", ``);
  }
  if (sequenceDiagram) {
    lines.push(`## Sequence`, ``, "```mermaid", sequenceDiagram.trim(), "```", ``);
  }
  if (dataflow) {
    lines.push(`## Data Flow`, ``, "```mermaid", dataflow.trim(), "```", ``);
  }

  if (example) {
    const langTag = (detectedLanguage || "").toLowerCase();
    lines.push(`## Usage Example`, ``, "```" + langTag, example.trim(), "```", ``);
  }

  if (edgeCases) lines.push(`## Edge Cases & Gotchas`, ``, edgeCases, ``);
  if (complexity) lines.push(`## Complexity & Performance`, ``, complexity, ``);

  lines.push(`---`, `*Generated by [PlainCode](https://plaincode-production.up.railway.app)*`);

  return lines.join("\n");
}

function buildJsDocBlock(entry: ApiEntry): string {
  const lines: string[] = ["/**", ` * ${entry.description}`];
  if (entry.params.length > 0) lines.push(` *`);
  for (const p of entry.params) {
    const name = p.optional ? `[${p.name}]` : p.name;
    lines.push(` * @param {${p.type}} ${name} ${p.description}`);
  }
  if (entry.returns && entry.returns.type) {
    lines.push(` * @returns {${entry.returns.type}} ${entry.returns.description}`);
  }
  for (const t of entry.throws) {
    lines.push(` * @throws {${t.type}} ${t.description}`);
  }
  lines.push(" */");
  return lines.join("\n");
}

function buildPythonDocstring(entry: ApiEntry): string {
  const lines: string[] = [`"""${entry.description}`, ``];
  if (entry.params.length > 0) {
    lines.push("Args:");
    for (const p of entry.params) {
      lines.push(`    ${p.name} (${p.type}): ${p.description}`);
    }
    lines.push("");
  }
  if (entry.returns && entry.returns.type) {
    lines.push("Returns:", `    ${entry.returns.type}: ${entry.returns.description}`, ``);
  }
  if (entry.throws.length > 0) {
    lines.push("Raises:");
    for (const t of entry.throws) {
      lines.push(`    ${t.type}: ${t.description}`);
    }
    lines.push("");
  }
  lines.push(`"""`);
  return lines.map((l, i) => (i === 0 ? l : "    " + l)).join("\n");
}

function buildGenericBlock(entry: ApiEntry): string {
  const lines: string[] = [`// ${entry.signature}`, `// ${entry.description}`];
  for (const p of entry.params) {
    lines.push(`//   @param ${p.name} (${p.type}) — ${p.description}`);
  }
  if (entry.returns?.type) {
    lines.push(`//   @returns ${entry.returns.type} — ${entry.returns.description}`);
  }
  for (const t of entry.throws) {
    lines.push(`//   @throws ${t.type} — ${t.description}`);
  }
  return lines.join("\n");
}

export function exportDocstrings(entries: ApiEntry[], detectedLanguage: string): string {
  if (entries.length === 0) return "";
  const lang = detectedLanguage.toLowerCase();
  const isJsTs = /(javascript|typescript|jsx|tsx|node|js|ts)/.test(lang);
  const isPython = /python|py/.test(lang);

  const builder = isJsTs
    ? buildJsDocBlock
    : isPython
      ? buildPythonDocstring
      : buildGenericBlock;

  return entries
    .map((e) => `${builder(e)}\n${e.signature}`)
    .join("\n\n");
}

export function exportDefendMarkdown(data: DefendExportData): string {
  const { repoUrl, defenseScore, builderType, assessment, weakSpots, answered } = data;
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const lines: string[] = [
    `# Defend Report`,
    ``,
    `**Repository:** ${repoUrl}  `,
    `**Date:** ${date}  `,
    `**Defense Score:** ${defenseScore}/100  `,
    builderType ? `**Builder Type:** ${builderType}  ` : "",
    ``,
  ].filter((l) => l !== undefined);

  if (assessment) {
    lines.push(`## Assessment`, ``, assessment, ``);
  }

  if (weakSpots.length > 0) {
    lines.push(`## Weak Spots`, ``);
    for (const spot of weakSpots) {
      lines.push(`- ${spot}`);
    }
    lines.push(``);
  }

  if (answered.length > 0) {
    lines.push(`## Q&A Breakdown`, ``);
    for (const a of answered) {
      lines.push(
        `### ${a.category} — ${a.score}/100`,
        ``,
        `**Question:** ${a.question}`,
        ``,
        `**Answer:** ${a.answer}`,
        ``,
        `**Feedback:** ${a.feedback}`,
        ``
      );
    }
  }

  lines.push(`---`, `*Generated by [PlainCode](https://plaincode-production.up.railway.app)*`);

  return lines.join("\n");
}
