"use client";
import { useEffect, useState } from "react";
import { GitPullRequest, Loader2, Github, ExternalLink, KeyRound } from "lucide-react";

interface Props {
  repoUrl: string;
  markdown: string;
  defaultPath: string;
}

interface GhStatus {
  configured: boolean;
  connected: boolean;
}

export function CommitDocsButton({ repoUrl, markdown, defaultPath }: Props) {
  const [status, setStatus] = useState<GhStatus | null>(null);
  const [path, setPath] = useState(defaultPath);
  const [usePat, setUsePat] = useState(false);
  const [pat, setPat] = useState("");
  const [committing, setCommitting] = useState(false);
  const [prUrl, setPrUrl] = useState("");
  const [error, setError] = useState("");

  useEffect(() => {
    let cancelled = false;
    fetch("/api/github/status")
      .then((r) => r.json())
      .then((d: GhStatus) => {
        if (!cancelled) setStatus(d);
      })
      .catch(() => {
        if (!cancelled) setStatus({ configured: false, connected: false });
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const commit = async () => {
    setError("");
    setPrUrl("");
    setCommitting(true);
    try {
      const res = await fetch("/api/document/commit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          repoUrl,
          files: [{ path, content: markdown }],
          prTitle: "Add documentation (PlainCode)",
          prBody: "Documentation generated by PlainCode.",
          ...(usePat && pat.trim() ? { token: pat.trim() } : {}),
        }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error ?? "Failed to open PR");
        return;
      }
      setPrUrl(data.url);
    } catch {
      setError("Could not reach GitHub. Try again.");
    } finally {
      setCommitting(false);
    }
  };

  if (!status) return null;

  const connected = status.connected;
  const canCommit = connected || (usePat && pat.trim().length > 0);

  return (
    <div className="rounded-lg border border-border bg-card p-4 space-y-3 section-fade-in">
      <div className="flex items-center gap-2 text-sm font-semibold text-foreground">
        <GitPullRequest className="h-4 w-4 text-indigo-500" />
        Commit docs to the repo
      </div>

      {prUrl ? (
        <a
          href={prUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1.5 text-sm text-indigo-500 hover:underline"
        >
          Pull request opened <ExternalLink className="h-3.5 w-3.5" />
        </a>
      ) : (
        <>
          <div className="space-y-1">
            <label className="text-xs text-muted-foreground">File path in repo</label>
            <input
              value={path}
              onChange={(e) => setPath(e.target.value)}
              className="w-full text-sm border border-border rounded-md px-3 py-1.5 bg-background font-mono focus:outline-none focus:ring-1 focus:ring-ring"
              placeholder="docs/DOCUMENTATION.md"
            />
          </div>

          {/* Auth: OAuth connect when available, plus the token fallback. */}
          {!connected && (
            <div className="space-y-2">
              {status.configured && !usePat && (
                <a
                  href="/api/github/auth"
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md border border-border text-xs font-medium hover:bg-accent transition-colors"
                >
                  <Github className="h-3.5 w-3.5" /> Connect GitHub
                </a>
              )}

              {!usePat ? (
                <button
                  onClick={() => setUsePat(true)}
                  className="block text-xs text-muted-foreground hover:text-foreground underline"
                >
                  {status.configured ? "or use a token instead" : "Use a GitHub token"}
                </button>
              ) : (
                <div className="space-y-1">
                  <label className="flex items-center gap-1 text-xs text-muted-foreground">
                    <KeyRound className="h-3 w-3" />
                    Fine-grained token with Contents + Pull requests write
                  </label>
                  <input
                    type="password"
                    value={pat}
                    onChange={(e) => setPat(e.target.value)}
                    placeholder="github_pat_..."
                    className="w-full text-sm border border-border rounded-md px-3 py-1.5 bg-background font-mono focus:outline-none focus:ring-1 focus:ring-ring"
                  />
                  <p className="text-[11px] text-muted-foreground">
                    Used once for this request and never stored.
                  </p>
                </div>
              )}
            </div>
          )}

          <button
            onClick={commit}
            disabled={!canCommit || committing || !path.trim()}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-primary text-primary-foreground text-xs font-medium hover:bg-primary/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {committing ? (
              <>
                <Loader2 className="h-3.5 w-3.5 animate-spin" /> Opening PR...
              </>
            ) : (
              <>
                <GitPullRequest className="h-3.5 w-3.5" /> Open docs PR
              </>
            )}
          </button>

          {error && <p className="text-xs text-destructive">{error}</p>}
        </>
      )}
    </div>
  );
}
